services:
  web:
    build:
      context: .
      dockerfile: src/internal_developer_portal/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db